# Generated by Django 4.0.2 on 2022-03-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='answer',
            field=models.TextField(max_length=50),
        ),
    ]
