# Generated by Django 4.0.2 on 2022-03-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_ans_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='answer',
            field=models.TextField(),
        ),
    ]
