# Generated by Django 4.0.2 on 2022-03-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_ans_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='q',
            old_name='answer',
            new_name='Qta',
        ),
    ]
