# Generated by Django 4.0.2 on 2022-03-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rename_answer_q_qta'),
    ]

    operations = [
        migrations.AddField(
            model_name='q',
            name='QUESTION2',
            field=models.CharField(default='SOME STRING', max_length=40),
        ),
    ]
