# Generated by Django 4.0.2 on 2022-03-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_q_question2'),
    ]

    operations = [
        migrations.AddField(
            model_name='q',
            name='Qta3',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
