# Generated by Django 4.0.2 on 2022-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_rename_qta_q_qta1_rename_question2_q_qta2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Q',
        ),
        migrations.AddField(
            model_name='ans',
            name='Qta1',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
