# Generated by Django 4.0.2 on 2022-03-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_delete_q_ans_qta1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qta1', models.CharField(default='SOME STRING', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ans',
        ),
    ]
