# Generated by Django 4.0.2 on 2022-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_q_op1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q',
            name='op1',
            field=models.CharField(default='', max_length=20),
        ),
    ]
