# Generated by Django 4.0.2 on 2022-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_alter_q_op1'),
    ]

    operations = [
        migrations.AddField(
            model_name='q',
            name='op2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='q',
            name='op3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='q',
            name='op4',
            field=models.CharField(default='', max_length=20),
        ),
    ]
