# Generated by Django 4.0.2 on 2022-03-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_q_op2_q_op3_q_op4'),
    ]

    operations = [
        migrations.AddField(
            model_name='q',
            name='correctop',
            field=models.CharField(default='', max_length=100),
        ),
    ]
