# Generated by Django 4.0.2 on 2022-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_q_correctop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Java',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qta1', models.CharField(default='SOME STRING', max_length=50)),
                ('op1', models.CharField(default='', max_length=20)),
                ('op2', models.CharField(default='', max_length=20)),
                ('op3', models.CharField(default='', max_length=20)),
                ('op4', models.CharField(default='', max_length=20)),
                ('correctop', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
